### ISSUE TITLE
Apple could not verify "Mizu.app" and make a user-friendly way of installing Mizu

### ISSUE THREAD

**Issue by JerbearGC** [esoxjem/Mizu#3]
Hi, I'm still kinda new to GitHub so I kindly ask to cut me some slack here and there. My point is when I tried to install Mizu, I couldn't see an installation method (I'm comparing this to Spicetify) so I was kind of confused for a bit. I did some research and tried to download version 1.0.1 from the releases section and saw two source code files. Me, being none wiser downloaded the .zip file and came to the realization that the app I was looking for was now there and instead I had something I shouldn't have. I deleted the .zip and with full rational thinking downloaded the same version but the .tar.gz file instead. Keep in mind, both said source-code. Anyway to cut the long story short, it didn't work and I checked with older versions (1.0 and 0.8) and found I was indeed tweaking and should have seen a package which was labelled Mizu.app. So point #1 is, there was no Mizu.app for version 1.0.1

Point #2 goes as follows. After downloading version 1.0, my plan was to just update it (somehow (I would cross that bridge when I get to it)). Trying to open Mizu led to this popup, 

<img width="267" alt="image" src="https://github.com/user-attachments/assets/30bf6913-0cf0-4134-baad-e132f83161ad">

Me being my newbie self on Mac, decided to keep pressing done and trying to reopen Mizu because I thought that MacOS would give up. It didn't. So that is point #2.

I hope this is helpful and hope you read this soon cuz I really like the concept and design of Mizu over others and I don't want to get Raycast just to get something similar (Acqua shortcut).

Thanks again

**Comment by esoxjem** [comment]
Hi @JerbearGC, thanks for writing. Let me have a look and get back to you

**Comment by esoxjem** [comment]
@JerbearGC regarding version 1.0.0, this is a standard error from macOS, if you don't download the app from the App Store. 

Here's the workaround when you see this error:
1.	Go to System Settings (or System Preferences)
2.	Click on Privacy & Security
3.	Scroll down to the Security section
4.	Under “Allow apps downloaded from,” you’ll see an option to allow the blocked app
5.	Click “Open Anyway” or “Allow” to permit the installation

Read more: https://support.apple.com/en-gb/102445

**Comment by JerbearGC** [comment]
Thank esoxjem for replying, the help is greatly appreciated. Sadly, it didn't work, I'm on Sequoia (15.0.1) and I think (based on the article) that Mizu has to be notarised by Apple or it needs to be on the App Store. Either way, it didn't work because in Sequoia (I'm on Apple Silicon btw) in the Security section there is no option to allow a blocked app, 

<img width="458" alt="image" src="https://github.com/user-attachments/assets/4c7dccc5-4c50-485d-af86-0f495d0e6925">

So yeah

**Comment by JerbearGC** [comment]
The only other option is App Store, instead of blocked apps. Additionally, the Advanced setting just says this:

<img width="458" alt="image" src="https://github.com/user-attachments/assets/17c1e644-bc74-448c-8c8c-2d612da0d962">


Proof of App Store option:

<img width="458" alt="image" src="https://github.com/user-attachments/assets/17c88991-ab50-4132-b2ee-f8df528aba88">

**Comment by JerbearGC** [comment]
Second crazy thing I just realized is, the app is working in the background. Mizu asked me to send notifications, but I thought it wouldn't work because the app wouldn't open. However, the notifications still work!

<img width="363" alt="image" src="https://github.com/user-attachments/assets/41b55887-4ada-4309-9d9a-7e1daf0d0007">

I have no idea what this means, whether it's running in the background or something?

I'll do more research

Edit:

The app is working in the background. Despite my Mac stopping me from opening it, it is open and working in the background. I never saw it before because I use my mac zoomed in. So I zoomed all the way out and there it was, chilling in my hidden bar:

<img width="363" alt="Screenshot 2024-11-18 at 9 32 58 PM" src="https://github.com/user-attachments/assets/e28ef13f-3f6f-40c9-983c-63f2890c1471">

**Comment by JerbearGC** [comment]
![Uploading Screenshot 2024-11-18 at 9.36.59 PM.png…]()


There she is, absolutely lovely.

Thanks for helping esoxjem

**Comment by JerbearGC** [comment]
<img width="363" alt="Screenshot 2024-11-18 at 9 36 59 PM" src="https://github.com/user-attachments/assets/d9966331-7372-4b23-9051-88c5a1ee6ba0">

There she is, absolutely lovely

Thanks for helping esoxjem, it was mighty appreciated honestly. Thanks again!

**Comment by esoxjem** [comment]
@JerbearGC that's great. This is a pretty old project and I haven't given it much love since. I will have a look if I can do something to improve the Apple Silicon setup. Might require some updates to the app. 

Thanks for reporting. I will close this issue for now!

**Comment by esoxjem** [comment]
@JerbearGC please try the latest release and see if it is any easier now

**Comment by JerbearGC** [comment]
Yoooo, much easier now, TYSM!!! Still working on it 1 year later huh? Dedication right there (Imma check out Luego asw). So far, yes Mizu has played a role in me drinking more water, works fine and genuinely I can't thank you enough, perfect RAM usage for my 8GB "beast" and runs in the background soooo great, no crashes which is not something I can say for the Apple Music app (but don't tell them that, they should already know). Some feedback would be as someone who drinks from a bottle and tends to finish said bottle a couple minutes after a Mizu notification (being prompted to remember bottle's existence by Mizu notification and then taking tons of swigs), I initially found the 30 min notification slider to be too long (weird I know). But looking back on it now and comparing it with how my use case has changed, for me 30 min is perfect. Though, maybe a button to say "I've drank water, remind me in the next 4 minutes or something" though I don't think this is necessary or even worth it tbh. So all in all, thank you again for updating/remembering Mizu (installation was much easier now) and hit me up again when a new release comes out, cuz it might not auto-update (that may be a feature that needs to be added actually).

**Comment by esoxjem** [comment]
Thanks @JerbearGC, I'll figure out how to add auto-update to it. In the meantime, fee free to click on "watch" on the repo, you will be email about new releases :)
